version: '3.7'

services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
  gateway:
    build:
      context: gateway
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/example_posts
  frontend:
    build:
      context: frontend
    depends_on:
      - gateway
    ports:
      - "8050:8050"